### ISSUE TITLE
Hard dependency on APPNAME=training

### ISSUE THREAD

**Issue by tbaums** [djannot/dcos-kubernetes-training#6]
I believe this line creates a hard dependency on the APPNAME variable being 'training'

https://github.com/djannot/dcos-kubernetes-training/blob/778bf7852af4e4244e9e4f7442b130eba00fcd23/student/options-kubernetes-cluster.json.template#L3

**Comment by djannot** [comment]
That's true, but the goal is not to let someone change this value.
There are many other places where it is hardcoded.

If you are looking for a way to deploy Kubernetes clusters with more flexibility, you should use this repo:
https://github.com/djannot/dcos-demos
